language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t ps901/docker-react -f Dockerfile.dev . 

script:
  -  docker run -e CI=true ps901/docker-react npm run test 